### ISSUE TITLE
Mod having no effects in 1.16.2

### ISSUE THREAD

**Issue by Eartelyna** [2Retr0/BedrockWaters#1]
The mod doesn't provides any crash or error while loading in 1.16.2 on v1.4.1, however, it does not have any effect while in game, the following screenshot was taken in a mushroom field biome : 
![2020-08-26_02 29 35](https://user-images.githubusercontent.com/69773913/91241622-a24df880-e745-11ea-9708-c38a195a3dad.png)
And here is the content of a log while launching only with this mod and fabric api on the client :

``` [02:23:42] [main/INFO]: Loading for game Minecraft 1.16.2
[02:23:43] [main/INFO]: [FabricLoader] Loading 41 mods: minecraft@1.16.2, bedrockwaters@1.4.1+1.16.2, fabric-networking-blockentity-v0@0.2.5+b50ffc7b4e, fabric-renderer-api-v1@0.2.13+eae12eb84e, fabric-screen-handler-api-v1@1.1.0+872498414e, fabric-keybindings-v0@0.2.0+3fa9f7c54e, fabric-command-api-v1@1.0.8+5ce533984e, fabricloader@0.9.1+build.205, fabric-tool-attribute-api-v1@1.2.2+ccce563e4e, fabric-renderer-indigo@0.3.4+5d32f5834e, fabric-structure-api-v1@1.0.0+516ece7c4e, fabric-containers-v0@0.1.8+045df74f4e, fabric-object-builder-api-v1@1.6.0+e81ec80b4e, fabric-item-api-v1@1.1.0+29679fd64e, fabric-events-interaction-v0@0.4.0+e2e6cdad4e, fabric-crash-report-info-v1@0.1.2+b7f9825d4e, fabric-game-rule-api-v1@1.0.1+91555cd14e, fabric-api-base@0.1.3+12a8474c4e, fabric-rendering-v0@1.1.0+534104904e, fabric-key-binding-api-v1@1.0.1+730711c64e, fabric-rendering-v1@1.2.0+fc24ff244e, fabric-rendering-data-attachment-v1@0.1.3+b7f9825d4e, fabric-resource-loader-v0@0.2.9+e5d3217f4e, fabric-textures-v0@1.0.4+eae12eb84e, fabric-content-registries-v0@0.1.9+059ea8664e, fabric-tag-extensions-v0@1.0.3+ac8e8c594e, fabric-rendering-fluids-v1@0.1.10+e5d3217f4e, fabric-commands-v0@0.2.0+52d308364e, fabric-registry-sync-v0@0.4.3+e5d3217f4e, fabric-blockrenderlayer-v1@1.1.4+c6a8ea894e, fabric-lifecycle-events-v1@1.2.0+74cc3b204e, fabric-mining-levels-v0@0.1.2+b764ce994e, fabric-renderer-registries-v1@2.1.0+e2862de64e, fabric-events-lifecycle-v0@0.2.0+16acbe5b4e, fabric-loot-tables-v1@1.0.0+fac8f3664e, fabric@0.19.0+build.398-1.16, fabric-item-groups-v0@0.2.0+438f96364e, fabric-models-v0@0.1.0+dfdb52d64e, fabric-particles-v1@0.2.1+0a6f2a704e, fabric-networking-v0@0.1.10+e00ecb5f4e, fabric-object-builders-v0@0.6.1+ba4afa574e
[02:23:44] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.1 Source=file:/C:/Users/PsychoNeko/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.8.1+build.21/sponge-mixin-0.8.1+build.21.jar Service=Knot/Fabric Env=CLIENT
[02:24:01] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', name='PROD'
[02:24:01] [main/INFO]: Setting user: Eartelyna
[02:24:01] [main/INFO]: [BedrockWaters] BedrockWaters initialized!
[02:24:01] [main/INFO]: [BedrockWaters] Modifying vanilla biome water attributes...
[02:24:01] [main/INFO]: [BedrockWaters] Finished!
[02:24:01] [main/INFO]: [Indigo] Registering Indigo renderer!
[02:24:02] [main/INFO]: Backend library: LWJGL version 3.2.2 build 10
[02:24:11] [main/INFO]: Narrator library for x64 successfully loaded
[02:24:11] [main/INFO]: Reloading ResourceManager: Default, BedrockWaters, Fabric Networking Block Entity (v0), Fabric Renderer API (v1), Fabric Screen Handler API (v1), Fabric Key Bindings (v0), Fabric Loader, Fabric Tool Attribute API (v1), Fabric Renderer - Indigo, Fabric Containers (v0), Fabric Object Builder API (v1), Fabric Item API (v1), Fabric Events Interaction (v0), Fabric Crash Report Info (v1), Fabric Game Rule API (v1), Fabric API Base, Fabric Rendering (v0), Fabric Key Binding API (v1), Fabric Rendering (v1), Fabric Rendering Data Attachment (v1), Fabric Resource Loader (v0), Fabric Textures (v0), Fabric Content Registries (v0), Fabric Tag Extensions (v0), Fabric Rendering Fluids (v1), Fabric Registry Sync (v0), Fabric BlockRenderLayer Registration (v1), Fabric Lifecycle Events (v1), Fabric Mining Levels (v0), Fabric Renderer Registries (v1), Fabric Events Lifecycle (v0), Fabric Loot Tables (v1), Fabric API, Fabric Item Groups (v0), Fabric Models (v0), Fabric Networking (v0), Fabric Object Builders (v0), VanillaTweaks_r128239.zip, restock-clock.zip
[02:24:38] [main/INFO]: OpenAL initialized.
[02:24:38] [main/INFO]: Sound engine started
[02:24:39] [main/INFO]: Created: 1024x1024x0 minecraft:textures/atlas/blocks.png-atlas
[02:24:39] [main/INFO]: Created: 256x128x0 minecraft:textures/atlas/signs.png-atlas
[02:24:39] [main/INFO]: Created: 1024x512x0 minecraft:textures/atlas/banner_patterns.png-atlas
[02:24:39] [main/INFO]: Created: 1024x512x0 minecraft:textures/atlas/shield_patterns.png-atlas
[02:24:39] [main/INFO]: Created: 256x256x0 minecraft:textures/atlas/chest.png-atlas
[02:24:39] [main/INFO]: Created: 512x256x0 minecraft:textures/atlas/beds.png-atlas
[02:24:39] [main/INFO]: Created: 512x256x0 minecraft:textures/atlas/shulker_boxes.png-atlas
[02:24:41] [main/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[02:24:41] [main/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[02:24:41] [main/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[02:24:56] [main/INFO]: Connecting to 213.64.113.171, 25567
[02:25:01] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', name='PROD'
[02:25:06] [main/FATAL]: Error executing task on Client
java.lang.NullPointerException: null
	at net.minecraft.class_269.method_1191(class_269.java:199) ~[intermediary-fabric-loader-0.9.1+build.205-1.16.2.jar:?]
	at net.minecraft.class_634.method_11099(class_634.java:2154) ~[intermediary-fabric-loader-0.9.1+build.205-1.16.2.jar:?]
	at net.minecraft.class_2755.method_11860(class_2755.java:122) ~[intermediary-fabric-loader-0.9.1+build.205-1.16.2.jar:?]
	at net.minecraft.class_2755.method_11054(class_2755.java:16) ~[intermediary-fabric-loader-0.9.1+build.205-1.16.2.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-fabric-loader-0.9.1+build.205-1.16.2.jar:?]
	at net.minecraft.class_2600$$Lambda$3559/487362589.run(Unknown Source) ~[?:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:144) [intermediary-fabric-loader-0.9.1+build.205-1.16.2.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [intermediary-fabric-loader-0.9.1+build.205-1.16.2.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:118) [intermediary-fabric-loader-0.9.1+build.205-1.16.2.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:103) [intermediary-fabric-loader-0.9.1+build.205-1.16.2.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:990) [intermediary-fabric-loader-0.9.1+build.205-1.16.2.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:656) [intermediary-fabric-loader-0.9.1+build.205-1.16.2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [intermediary-fabric-loader-0.9.1+build.205-1.16.2.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) [fabric-loader-0.9.1+build.205.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-loader-0.9.1+build.205.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.9.1+build.205.jar:?]
[02:25:06] [main/FATAL]: Error executing task on Client
java.lang.NullPointerException: null
	at net.minecraft.class_269.method_1191(class_269.java:199) ~[intermediary-fabric-loader-0.9.1+build.205-1.16.2.jar:?]
	at net.minecraft.class_634.method_11099(class_634.java:2154) ~[intermediary-fabric-loader-0.9.1+build.205-1.16.2.jar:?]
	at net.minecraft.class_2755.method_11860(class_2755.java:122) ~[intermediary-fabric-loader-0.9.1+build.205-1.16.2.jar:?]
	at net.minecraft.class_2755.method_11054(class_2755.java:16) ~[intermediary-fabric-loader-0.9.1+build.205-1.16.2.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-fabric-loader-0.9.1+build.205-1.16.2.jar:?]
	at net.minecraft.class_2600$$Lambda$3559/487362589.run(Unknown Source) ~[?:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:144) [intermediary-fabric-loader-0.9.1+build.205-1.16.2.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [intermediary-fabric-loader-0.9.1+build.205-1.16.2.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:118) [intermediary-fabric-loader-0.9.1+build.205-1.16.2.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:103) [intermediary-fabric-loader-0.9.1+build.205-1.16.2.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:990) [intermediary-fabric-loader-0.9.1+build.205-1.16.2.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:656) [intermediary-fabric-loader-0.9.1+build.205-1.16.2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [intermediary-fabric-loader-0.9.1+build.205-1.16.2.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) [fabric-loader-0.9.1+build.205.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-loader-0.9.1+build.205.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.9.1+build.205.jar:?]
[02:25:07] [main/INFO]: Loaded 595 advancements
[02:25:07] [main/INFO]: [CHAT] Eartelyna joined the game
[02:25:07] [main/INFO]: [CHAT] You have no new mail.
[02:25:29] [main/INFO]: Stopping!

**Comment by 2Retr0** [comment]
Took a look into it and it seems to be an issue only when playing on any server (i.e. not single player). I'll have to see what I can do when I have a little more free time, but thank you for bring this to my attention.

**Comment by mthvrs** [comment]
Can confirm that in 1.16.3 it doesn't work when playing on a server. I *think* it did work when I had it both on the server and the client but I can't say so for sure.

**Comment by Hiasinsu** [comment]
Confirmed with 1.16.4, it works in singleplayer but has no effect on any server.

**Comment by 2Retr0** [comment]
Update I've pushed to curseforge today should address this issue. Install the mod on the dedicated server and anyone joining should be able to see the altered water colors.
