### ISSUE TITLE
Crash when trying to switch to mob in spectator mode

### ISSUE THREAD

**Issue by Bobronium** [2Retr0/BedrockWaters#5]
### Steps to reproduce
- Switch to spectator mode 
- click LMB on any mob

Game will be stuck for a couple of seconds and then will crash.
### Part of crash report:
```
Description: Unexpected error

java.lang.ClassCastException: class net.minecraft.class_1472 cannot be cast to class net.minecraft.class_746 (net.minecraft.class_1472 and net.minecraft.class_746 are in unnamed module of loader net.fabricmc.loader.launch.knot.KnotClassLoader @33ecda92)
	at net.minecraft.class_758.handler$zgj000$onApplyFogAboveWater(class_758.java:545)
	at net.minecraft.class_758.method_3211(class_758.java:243)
	at net.minecraft.class_761.method_22710(class_761.java:1123)
	at net.minecraft.class_757.method_3188(class_757.java:727)
	at net.minecraft.class_757.method_3192(class_757.java:546)
	at net.minecraft.class_310.method_1523(class_310.java:1048)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
```
### Full crash report
[crash-2021-02-10_20.16.43-client.txt](https://github.com/2Retr0/BedrockWaters/files/5960070/crash-2021-02-10_20.16.43-client.txt)

Bug occurs only when this mod is installed, tried to start the game with only Fabric API and BedrockWaters and bug was still reproducible.

**Comment by 2Retr0** [comment]
Fixed in version 1.7.0
